# Generated by Django 4.0.4 on 2022-05-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Q2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta_operation',
            name='id',
        ),
        migrations.AlterField(
            model_name='meta_operation',
            name='bin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Q2.bin'),
        ),
    ]
